VERSION 0.8
FROM ../+chef-cook

ARG --global --required DIR
CACHE ./target/
WORKDIR /usr/local/src/pypi/$DIR

test:
    RUN uv run pytest

bench:
    RUN uv run richbench benches --markdown

bash:
    RUN --interactive bash
