name: Tests

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: PyO3/maturin-action@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: pre-commit/action@v3.0.0

  tests:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v3
      - uses: PyO3/maturin-action@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Setup Python Venv
        run: |
          pip install --upgrade pip
          python3.9 -m venv .venv
          source .venv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
      # - name: Build and test
      #   run: maturin develop --release --extras=dev
      - name: Rust tests
        run: cargo test --release
      # - name: Python tests
      #   run: |
      #     pip install pytest
      #     pytest
