[package]
name = "abd-clam"
version = "0.23.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "abd_clam"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
