VERSION 0.8
FROM ../+chef-cook

ARG --global --required DIR
CACHE ./target/
WORKDIR /usr/local/src/python/$DIR

pytest:
    FROM ../+chef-cook
    RUN maturin develop --release --strip --extras=dev
    RUN python -m pytest -v

bash:
    RUN --interactive bash
