name: Publish

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  upload-linux:
    uses: ./.github/workflows/upload-linux.yml

  upload-macos:
    uses: ./.github/workflows/upload-macos.yml

  upload-windows:
    uses: ./.github/workflows/upload-windows.yml

  upload-sdist:
    uses: ./.github/workflows/upload-sdist.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [upload-linux, upload-macos, upload-windows, upload-sdist]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *
