name: Build | Sdist

on: [workflow_call]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch workspace members
        run: git submodule update --init
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
            command: sdist
            args: --out dist
      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
            name: wheels
            path: dist
