VERSION 0.7
FROM ../+build-cache

ARG --required DIR
WORKDIR /usr/local/src/crates/$DIR

test:
    RUN cargo test

publish:
    ARG --required EARTHLY_PUSH
    IF [ "$EARTHLY_PUSH" = "true" ]
        ARG --required CARGO_REGISTRY_TOKEN
        ENV CARGO_REGISTRY_TOKEN
        RUN cargo publish
    ELSE
        RUN cargo publish --dry-run
    END
    RUN --interactive bash

bash:
    RUN --interactive bash
