name: Clippy

on: [push]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: rustup component add clippy
      - name: Run
        run: cargo clippy -- -D warnings
