name: Tests | Linux

on: [workflow_call]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Fetch workspace members
        run: git submodule update --init
      - name: Install | Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: |
            clippy
            rustfmt
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install | Poetry
        uses: abatilo/actions-poetry@v2
      - name: Poetry | Config
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - name: Poetry | Cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-linux-${{ hashFiles('poetry.lock') }}
      - name: Poetry | Install
        run: poetry install --no-interaction
      - name: Maturin | Develop
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          args: --release
      - name: Matrix | Test
        run: |
          cargo test --release
          poetry run python -m unittest discover python
